name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew buildDebug
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: false # IMPORTANT: allow pipeline to continue to Android Test Report step
      
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
  sonar:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: SonarCloud Scan
          run: ./gradlew jacocoTestReport sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=andersonrsoares_marleyspoon-code-challenge -Dsonar.projectName=marleyspoon-code-challenge -Dsonar.sources=src/main/java -Dsonar.java.binaries=build/tmp/kotlin-classes/devDebug -Dsonar.language=kotlin -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/report.xml -Dsonar.exclusions="**/*.js,**/*.css,**/*.html" -Dsonar.java.coveragePlugin=jacoco -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=andersonrsoares --stacktrace
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Link to SonarCloud Report
          run: echo "hhttps://sonarcloud.io/dashboard?id=andersonrsoares_marleyspoon-code-challenge"
          
  testemulator:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck 
      
